Repository Temu4/a-level-fe-homeworks-2022, pull requests merged in 2022-05, with the labels that each got.

#14 hw-1
  students/M1lya1/hw-1/index.html
  students/M1lya1/hw-1/script.js
Labels: hw-1

#18 Second HomeWork
  students/Vladimir12241/hw-2/answers_1.md
  students/Vladimir12241/hw-2/answers_2.md
Labels: hw-2

#19 hw-2
  students/AntonBakaiev/hw-2/answers_1.md
  students/AntonBakaiev/hw-2/answers_2.md
Labels: hw-2

#20 Homework 2
  students/zima7/hw-2/answers_1.md
  students/zima7/hw-2/answers_2.md
Labels: hw-2

#21 add hw-2
  students/NikLitv/hw-2/answer_1.md
  students/NikLitv/hw-2/answer_2.md
Labels: hw-2

#15 hw-2
  students/M1lya1/hw-2/read.md
Labels: hw-2

#23 home work 2
  students/fill0s0fear/hw-2/answers_1.md
  students/fill0s0fear/hw-2/answers_2.md
Labels: hw-2

#24 home work 3
  students/fill0s0fear/hw-3/answers_1.md
  students/fill0s0fear/hw-3/answers_2.md
Labels: hw-3

#76 hw-2
  students/Gotem888/hw-2/answers_1.md
  students/Gotem888/hw-2/answers_2.md
Labels: hw-2

#37 hw-1
  students/FlyStriker/hw-1/index.css
  students/FlyStriker/hw-1/index.html
  students/FlyStriker/hw-1/index.js
Labels: hw-1, [done]

#38 hw-2
  students/FlyStriker/hw-2/answer_1.md
  students/FlyStriker/hw-2/answer_2.md
Labels: hw-2, [done]

#62 add hw-3
  students/AnastasiaPletser/hw-3/answers_1.md
  students/AnastasiaPletser/hw-3/answers_2.md
Labels: hw-3, [done]

#50 Hw 4
  students/Timajeem/hw4/index.html
  students/Timajeem/hw4/index.js
Labels: [changes-required], hw-4

#40 HW2_Tsigulov
  students/Sigul4/hw2/HW2.txt
Labels: hw-2, [done]

#35 HW2
  students/Mish535655/HW2/answers_1.md
  students/Mish535655/HW2/answers_2.md
Labels: hw-2, [done]

#34 HomeWork 3
  students/zima7/hw-3/answers_1.md
  students/zima7/hw-3/answers_2.md
Labels: hw-3, [done]

#30 add hw-3
  students/AntonBakaiev/hw-3/answers_1.md
  students/AntonBakaiev/hw-3/answers_2.md
Labels: hw-3, [done]

#26 Hw 3
  students/Vladimir12241/hw-3/answers_1.md
  students/Vladimir12241/hw-3/answers_2.md
Labels: hw-3, [done]

#25 Hw 3
  students/M1lya1/hw-3/task1.md
  students/M1lya1/hw-3/task2.md
Labels: hw-3, [changes-required]
