Repository Temu4/a-level-fe-homeworks-2022, pull requests merged in 2022-08, with the labels that each got.

#42 hw-4
  students/FlyStriker/README.md
  students/FlyStriker/hw-4/answer.js
Labels: hw-4

#43 home work 4
  students/fill0s0fear/hw-4/answers_1.js
  students/fill0s0fear/hw-4/answers_2.js
Labels: hw-4

#46 Hw 4
  students/AntonBakaiev/hw-4/answer.js
Labels: [changes-required], hw-4

#51 HW-4
  students/Vladimir12241/hw-4/Readme.md
  students/Vladimir12241/hw-4/answer.js
  students/Vladimir12241/hw-4/index.html
Labels: hw-4

#52 HomeWork 4
  students/zima7/hw-4/answers_1.js
  students/zima7/hw-4/answers_2.js
Labels: hw-4

#53 HW4
  students/Misha535655/HW4/answer.js
  students/Misha535655/HW4/index.html
Labels: hw-4

#61 add 2 files hw2
  students/AnastasiaPletser/hw-2/answers_1.md
  students/AnastasiaPletser/hw-2/answers_2.md
Labels: hw-1, hw-2, [changes-required]

#79 repeat hw-1
  students/Timajeem/hw-1/index.html
  students/Timajeem/hw-1/index.js
  students/Timajeem/hw-1/style.css
Labels: hw-1, [changes-required]

#91 repeat-hw-2
  students/Timajeem/hw-2/index.html
  students/Timajeem/hw-2/index.js
Labels: hw-2

#97 hw-2
  students/AirDray1/hw-2/answer_1.md
  students/AirDray1/hw-2/answer_2.md
  students/AirDray1/hw-2/index.html
  students/AirDray1/hw-2/src/index.js
Labels: hw-2

#83 hw-3
  students/gotem888/hw-3/answers_1.md
  students/gotem888/hw-3/answers_2.md
Labels: hw-3

#98 hw-3
  students/AirDray1/hw-3/Task_1.md
  students/AirDray1/hw-3/Task_2.md
  students/AirDray1/hw-3/img/task1(1).png
  students/AirDray1/hw-3/img/task1(2).png
  students/AirDray1/hw-3/img/task2.png
  students/AirDray1/hw-3/index.html
  students/AirDray1/hw-3/src/index.js
  students/airdray1/hw-3/img/task1(1).png
  students/airdray1/hw-3/img/task1(2).png
  students/airdray1/hw-3/img/task2.png
Labels: hw-3

#55 Hw 4
  students/M1lya1/hw-4/answer1.js
  students/M1lya1/hw-4/answer2.js
Labels: hw-4

#65 HW4
  students/AnastasiaPletser/hw-4/answer_1.js
  students/AnastasiaPletser/hw-4/answer_2.md
Labels: hw-4

#82 hw-4
  students/dariaboyko/hw-3/task1.md
  students/dariaboyko/hw-3/task2.md
  students/dariaboyko/hw-4/script.js
Labels: hw-4

#99 hw-4
  students/airdray1/hw-4/ReadME.md
  students/airdray1/hw-4/img/advanced1.png
  students/airdray1/hw-4/img/advanced2.png
  students/airdray1/hw-4/img/advanced3.png
  students/airdray1/hw-4/img/bank-card.png
  students/airdray1/hw-4/img/bankCrad-pattern.png
  students/airdray1/hw-4/img/e-mail-pattern.png
  students/airdray1/hw-4/img/example1.png
  students/airdray1/hw-4/img/exampleCode1.png
  students/airdray1/hw-4/img/exampleCode2.png
  students/airdray1/hw-4/img/phoneNumber-pattern.png
  students/airdray1/hw-4/img/result1(2).png
  students/airdray1/hw-4/img/result1.png
  students/airdray1/hw-4/img/result2(2).png
  students/airdray1/hw-4/img/result2.png
  students/airdray1/hw-4/img/task1.png
  students/airdray1/hw-4/img/verifyResulr.png
  students/airdray1/hw-4/index.html
  students/airdray1/hw-4/src/index.js
Labels: hw-4

#108 add hw-4
  students/msemerni/hw-4/index.html
  students/msemerni/hw-4/js/index.js
Labels: [changes-required], hw-4

#121 Hw4 tsigulov
  students/Sigul4/hw-4/answer.js
Labels: [changes-required], hw-4

#54 hw-5
  students/M1lya1/hw-5/answer.js
Labels: hw-5

#57 HomeWork 5
  students/zima7/hw-5/answer.js
Labels: hw-5

#59 Hw 5
  students/AntonBakaiev/hw-5/answer.js
Labels: [changes-required], hw-5

#60 add hw-5
  students/FlyStriker/hw-5/answer_1.js
  students/FlyStriker/hw-5/answer_2.js
Labels: hw-5

#63 hw-5
  students/Timajeem/hw-5/index.html
  students/Timajeem/hw-5/index.js
Labels: hw-5

#64 HW-5
  students/Vladimir12241/hw-5/answer.js
Labels: hw-5

#66 hw5
  students/AnastasiaPletser/answer_1.js
  students/AnastasiaPletser/answer_2.js
  students/AnastasiaPletser/answer_3.js
Labels: hw-5

#73 home work 5
  students/fill0s0fear/hw-5/answer.js
Labels: hw-5

#75 HW5
  students/Misha535655/HW5/index.html
  students/Misha535655/HW5/index.js
Labels: hw-5

#86 hw-5
  students/dariaboyko/hw-5/script.js
Labels: hw-5

#109 add hw-5
  students/msemerni/hw-5/index.html
  students/msemerni/hw-5/js/index.js
Labels: [changes-required], hw-5

#145 hw-1
  students/Sigul4/hw-1/page.html
  students/Sigul4/hw-1/style.css
Labels: hw-1

#148 hw-3
  students/Sigul4/hw-3/readme.md
Labels: hw-3

#115 Hw 4
  students/Gotem888/hw-4/index.html
  students/Gotem888/hw-4/scripts.js
Labels: hw-4

#117 Hw 5
  students/Gotem888/hw-5/answer.js
Labels: hw-5

#149 Hw 5
  students/Sigul4/hw-5/answer.js
  students/Sigul4/hw2/HW2.txt
Labels: hw-5

#147 Hw 6+7
  students/Sigul4/hw-6+7/task-1.js
  students/Sigul4/hw-6+7/task-2.js
  students/Sigul4/hw-6+7/task-3.js
Labels: hw-6+7

#135 Hw 6 7
  students/Gotem888/hw-6-7/task-1.js
  students/Gotem888/hw-6-7/task-2.js
  students/Gotem888/hw-6-7/task-3.js
Labels: hw-6+7

#112 hw-6+7
  students/AnastasiaPletser/hw-6+7/task-1.js
  students/AnastasiaPletser/hw-6+7/task-2.js
  students/AnastasiaPletser/hw-6+7/task-3.js
Labels: hw-6+7

#110 add hw-6+7
  students/msemerni/hw-6+7/index.html
  students/msemerni/hw-6+7/js/task-1.js
  students/msemerni/hw-6+7/js/task-2.js
  students/msemerni/hw-6+7/js/task-3.js
Labels: [changes-required], hw-6+7

#102 hw-(6+7)
  students/Airdray1/hw-(6+7)/ReadME.md
  students/Airdray1/hw-(6+7)/img/output1(2).png
  students/Airdray1/hw-(6+7)/img/output1.png
  students/Airdray1/hw-(6+7)/img/output2(2).png
  students/Airdray1/hw-(6+7)/img/output2.png
  students/Airdray1/hw-(6+7)/img/output3.png
  students/Airdray1/hw-(6+7)/img/result1(2).png
  students/Airdray1/hw-(6+7)/img/result1.png
  students/Airdray1/hw-(6+7)/img/result2.png
  students/Airdray1/hw-(6+7)/img/result3.png
  students/Airdray1/hw-(6+7)/img/task1.png
  students/Airdray1/hw-(6+7)/img/task2.png
  students/Airdray1/hw-(6+7)/img/task3.png
  students/Airdray1/hw-(6+7)/index.html
  students/Airdray1/hw-(6+7)/src/task-1.js
  students/Airdray1/hw-(6+7)/src/task-2.js
  students/Airdray1/hw-(6+7)/src/task-3.js
Labels: hw-6+7

#92 add hw-6-7
  students/FlyStr1ker/hw-6-7/task-1.js
  students/FlyStr1ker/hw-6-7/task-2.js
  students/FlyStr1ker/hw-6-7/task-3.js
Labels: hw-6+7

#87 hw-6+7
  students/dariaboyko/hw-6+7/task-1.js
  students/dariaboyko/hw-6+7/task-2.js
  students/dariaboyko/hw-6+7/task-3.js
Labels: hw-6+7

#78 HW6-7
  students/Misha535655/HW6-7/test-1.js
  students/Misha535655/HW6-7/test-2.js
  students/Misha535655/HW6-7/test-3.js
Labels: hw-6+7

#77 HW-6,7
  students/Vladimir12241/hw-6,7/answers1.js
  students/Vladimir12241/hw-6,7/answers2.js
  students/Vladimir12241/hw-6,7/answers3.js
Labels: hw-6+7

#74 home work 6+7
  students/fill0s0fear/hw-6+7/task-1.js
  students/fill0s0fear/hw-6+7/task-2.js
  students/fill0s0fear/hw-6+7/task-3.js
Labels: hw-6+7

#72 HomeWork 6+7
  students/zima7/hw-6+7/task-1.js
  students/zima7/hw-6+7/task-2.js
  students/zima7/hw-6+7/task-3.js
Labels: hw-6+7

#71 hw-6+7
  students/AntonBakaiev/hw-6+7/Task-1.js
  students/AntonBakaiev/hw-6+7/task-2.js
  students/AntonBakaiev/hw-6+7/task-3.js
Labels: [changes-required], hw-6+7

#68 HW 6-7
  students/M1lya1/HW 6-7/answer1.js
  students/M1lya1/HW 6-7/answer2.js
  students/M1lya1/HW 6-7/answer3.js
Labels: hw-6+7

#84 hw-8
  students/Misha535655/hw-8/task-1.js
  students/Misha535655/hw-8/task-2.js
  students/Misha535655/hw-8/task-3.js
Labels: hw-8

#88 Hw 8
  students/AntonBakaiev/hw-8/task-1.js
  students/AntonBakaiev/hw-8/task-2.js
  students/AntonBakaiev/hw-8/task-3.js
Labels: [changes-required], hw-8

#89 hw-8
  students/dariaboyko/hw-8/task-1.js
  students/dariaboyko/hw-8/task-2.js
  students/dariaboyko/hw-8/task-3.js
Labels: hw-8

#93 HomeWork 8
  students/zima7/hw-8/task-1.js
  students/zima7/hw-8/task-2.js
  students/zima7/hw-8/task-3.js
Labels: hw-8

#94 hw-8
  students/Vladimir12241/hw-8/task-1.js
  students/Vladimir12241/hw-8/task-2.js
  students/Vladimir12241/hw-8/task-3.js
Labels: hw-8

#96 hw-8
  students/M1lya1/hw-8/task1.js
  students/M1lya1/hw-8/task2.js
  students/M1lya1/hw-8/task3.js
Labels: hw-8

#104 hw-8
  students/FlyStr1ker/hw-8/task-1.js
  students/FlyStr1ker/hw-8/task-2.js
  students/FlyStr1ker/hw-8/task-3.js
Labels: hw-8

#111 add hw-8
  students/msemerni/hw-8/index.html
  students/msemerni/hw-8/js/task-1.js
  students/msemerni/hw-8/js/task-2.js
  students/msemerni/hw-8/js/task-3.js
Labels: [changes-required], hw-8

#114 hw-8
  students/AirDray1/hw-8/ReadME.md
  students/AirDray1/hw-8/img/code1.png
  students/AirDray1/hw-8/img/code2.png
  students/AirDray1/hw-8/img/code3.png
  students/AirDray1/hw-8/img/output1.png
  students/AirDray1/hw-8/img/output2.png
  students/AirDray1/hw-8/img/output3.png
  students/AirDray1/hw-8/img/task1.png
  students/AirDray1/hw-8/img/task2.png
  students/AirDray1/hw-8/img/task3.png
  students/AirDray1/hw-8/index.html
  students/AirDray1/hw-8/src/task-1.js
  students/AirDray1/hw-8/src/task-2.js
  students/AirDray1/hw-8/src/task-3.js
Labels: hw-8

#134 Hw8 tsigulov
  students/Sigul4/hw-8/task-1.js
  students/Sigul4/hw-8/task-2.js
  students/Sigul4/hw-8/task-3.js
Labels: [changes-required], hw-8

#138 hw-8
  students/AnastasiaPletser/hw-8/task-1.js
  students/AnastasiaPletser/hw-8/task-2.js
  students/AnastasiaPletser/hw-8/task-3.js
Labels: hw-8

#164 hw-8
  students/fill0s0fear/hw-8/task-1.js
  students/fill0s0fear/hw-8/task-2.js
  students/fill0s0fear/hw-8/task-3.js
Labels: hw-8

#136 Hw 8
  students/Gotem888/hw-8/task-1.js
  students/Gotem888/hw-8/task-2.js
  students/Gotem888/hw-8/task-3.js
Labels: hw-8

#153 first hw
  students/leatris/hw-1/index.html
  students/leatris/hw-1/index.js
Labels: hw-1

#154 second hw
  students/leatris/hw-2/answers _1.md
  students/leatris/hw-2/answers_2.md
Labels: hw-2

#155 third hw
  students/leatris/hw-3/answers_1.md
  students/leatris/hw-3/answers_2.md
Labels: hw-3

#119 dom-practice
  students/msemerni/dom-practice/README.md
  students/msemerni/dom-practice/css/styles.css
  students/msemerni/dom-practice/fonts/Quantico/OFL.txt
  students/msemerni/dom-practice/fonts/Quantico/Quantico-Bold.ttf
  students/msemerni/dom-practice/fonts/Quantico/Quantico-BoldItalic.ttf
  students/msemerni/dom-practice/fonts/Quantico/Quantico-Italic.ttf
  students/msemerni/dom-practice/fonts/Quantico/Quantico-Regular.ttf
  students/msemerni/dom-practice/img/background.png
  students/msemerni/dom-practice/img/ezh.png
  students/msemerni/dom-practice/img/logo_pig.png
  students/msemerni/dom-practice/img/losyash.png
  students/msemerni/dom-practice/img/nyusha.png
  students/msemerni/dom-practice/img/pin.png
  students/msemerni/dom-practice/index.html
  students/msemerni/dom-practice/js/index.js
  students/msemerni/dom-practice/js/items.js
Labels: [changes-required], dom-practice

#131 hw-9
  students/Misha535655/hw-9/task-1.js
Labels: hw-9

#139 hw-9
  students/AnastasiaPletser/hw-9/task-1.js
Labels: hw-9

#141 HomeWork 9
  students/zima7/hw-9/task-1.js
Labels: hw-9

#142 hw-9
  students/AntonBakaiev/hw-9/task-1.js
Labels: hw-9

#143 Hw 9
  students/M1lya1/hw-9/answer.js
Labels: hw-9

#152 Hw 9
  students/Sigul4/hw-9/task.js
Labels: hw-9

#157 HW-9
  students/Vladimir12241/hw-9/task-1.js
Labels: hw-9

#165 hw-9
  students/fill0s0fear/hw-9/task-1.js
Labels: hw-9
