Repository Temu4/a-level-fe-homeworks-2022, pull requests merged in 2022-06, with the labels that each got.

#33 add third homework
  students/tony7kh/hw-3/answers_1.md
  students/tony7kh/hw-3/answers_2.md
Labels: hw-3

#39 hw-3
  students/FlyStriker/hw-3/answer_1.md
  students/FlyStriker/hw-3/answer_2.md
Labels: hw-3

#67 Hw 6+7
  students/tony7kh/hw-6+7/task-1.js
  students/tony7kh/hw-6+7/task-2.js
  students/tony7kh/hw-6+7/task-3.js
Labels: [done], hw-6+7

#105 add hw-1
  students/msemerni/hw-1/answers_2.md
  students/msemerni/hw-1/index.html
  students/msemerni/hw-1/js/index.js
Labels: hw-1, [done]

#106 add hw-2
  students/msemerni/hw-2/answers_2.md
Labels: hw-2, [done]

#107 add hw-3
  students/msemerni/hw-3/answers_3.md
Labels: hw-3, [done]

#137 add hw-9
  students/msemerni/hw-9/index.html
  students/msemerni/hw-9/js/task-1.js
Labels: [done], hw-9

#95 Hw 1
  students/AirDray1/hw-1/README.md
  students/AirDray1/hw-1/index.html
Labels: hw-1

#103 hw-1
  students/AnastasiaPletser/hw-1/index.html
  students/AnastasiaPletser/hw-1/index.js
Labels: hw-1, [done]

#80 hw-2
  students/dariaboyko/hw-2/task1.md
  students/dariaboyko/hw-2/task2.md
Labels: hw-2, [done]

#140 hw-9
  students/FlyStriker/hw-9/task-1.js
Labels: [done], hw-9

#45 add 4 homework
  students/tony7kh/hw-4/answer.js
Labels: [done], hw-4

#56 add hw 5
  students/tony7kh/hw-5/answers.js
Labels: [done], hw-5

#85 add 8 hw
  students/tony7kh/hw-8/task-1.js
  students/tony7kh/hw-8/task-2.js
  students/tony7kh/hw-8/task-3.js
Labels: [changes-required], hw-8
